[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
spectra_vault = "JBagp4qXz26XMHce1tXMpEwgVKPBpRGj7ejvsJXaoQhH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# For production: replace with RPC Fast endpoint
# cluster = "https://your-endpoint.rpcfast.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
